//! SIMD polyphase half-band oversampling, 8x total in three cascaded 2x stages.
//!
//! Specification section 2 and `CLAUDE.md` §2 require every non-linear stage to
//! run inside an 8x oversampled sub-pipeline built from polyphase half-band
//! filters.
//!
//! # Why half-band
//!
//! A half-band FIR of odd length `N = 2*TAPS - 1` designed with cutoff at
//! `fs/4` has the property that every tap at an even offset from the centre is
//! exactly zero, and the centre tap is exactly `0.5`. Splitting it into its two
//! polyphase branches
//!
//! ```text
//! e0[i] = h[2i]      (TAPS coefficients, symmetric)
//! e1[i] = h[2i + 1]  (all zero except e1[TAPS - 1] = 0.5)
//! ```
//!
//! turns one of the two branches into a bare delay. Interpolation therefore
//! costs a single `TAPS`-long dot product per *pair* of output samples, and
//! decimation costs one dot product per input pair. That is half the work of a
//! general FIR at the same stopband attenuation.
//!
//! # Filter design
//!
//! Coefficients are generated by [`design_halfband`] at `prepare()` time using a
//! Kaiser-windowed ideal half-band prototype:
//!
//! ```text
//! h[k] = 0.5 * sinc(0.5 * (k - M)) * kaiser(k, N, beta),   M = (N - 1) / 2
//! beta = 0.1102 * (A - 8.7)                                 (Kaiser, A > 50 dB)
//! ```
//!
//! The three stages are sized for progressively looser requirements, because
//! after stage 1 the signal already occupies only the lowest eighth of the
//! 8x band:
//!
//! | Stage | Rate      | `TAPS` | `N` | Design `A` | Stopband edge |
//! |-------|-----------|--------|-----|------------|---------------|
//! | 1     | 1x <-> 2x | 48     | 95  | 100 dB     | 0.284 * 2fs   |
//! | 2     | 2x <-> 4x | 16     | 31  | 80 dB      | 0.334 * 4fs   |
//! | 3     | 4x <-> 8x | 8      | 15  | 70 dB      | 0.404 * 8fs   |
//!
//! Only stage 1 sets the audible alias floor: images that fold back below
//! 20 kHz at a 48 kHz host rate come from above 28 kHz, which sits inside
//! stage 1's 100 dB stopband. The looser stages 2 and 3 fold their residue into
//! 21 kHz..Nyquist of the *intermediate* rates, where stage 1 removes it.
//!
//! # Latency
//!
//! Each stage contributes a group delay of `M` samples at its own upper rate on
//! the way up and `M` more on the way down, i.e. `2 * M / factor` host samples.
//! See [`Oversampler8x::latency_samples`].

use wide::f32x8;

use super::denormal::flush;

/// Delay-line length of a single half-band stage. A power of two so the write
/// pointer can wrap with a mask instead of a modulo, and large enough for the
/// longest branch in use (`TAPS = 48`).
const LINE: usize = 64;

/// Stage 1 polyphase branch length (`N = 95`).
pub const STAGE1_TAPS: usize = 48;
/// Stage 2 polyphase branch length (`N = 31`).
pub const STAGE2_TAPS: usize = 16;
/// Stage 3 polyphase branch length (`N = 15`).
pub const STAGE3_TAPS: usize = 8;

/// Stopband attenuation targets used to derive each stage's Kaiser `beta`.
const STAGE1_ATTENUATION_DB: f64 = 100.0;
const STAGE2_ATTENUATION_DB: f64 = 80.0;
const STAGE3_ATTENUATION_DB: f64 = 70.0;

/// Zeroth-order modified Bessel function of the first kind.
///
/// Evaluated by its Maclaurin series `I0(x) = sum_k ((x/2)^k / k!)^2`, which
/// converges in well under 40 terms for the `beta <= 11` range used by the
/// Kaiser windows here. Only called during `prepare()` and, for the same
/// window shape, by the resampler in [`crate::ir`].
pub(crate) fn bessel_i0(x: f64) -> f64 {
    let half_x = x * 0.5;
    let mut term = 1.0f64;
    let mut sum = 1.0f64;
    for k in 1..64 {
        let ratio = half_x / k as f64;
        term *= ratio * ratio;
        sum += term;
        if term < sum * 1.0e-17 {
            break;
        }
    }
    sum
}

/// Normalized sinc, `sin(pi*x) / (pi*x)`, with the removable singularity at
/// `x == 0` filled in.
pub(crate) fn sinc(x: f64) -> f64 {
    if x.abs() < 1.0e-12 {
        1.0
    } else {
        let pix = std::f64::consts::PI * x;
        pix.sin() / pix
    }
}

/// Generates the `e0` polyphase branch of a Kaiser-windowed half-band FIR.
///
/// The returned branch is scaled so that `sum(e0) == 0.5` exactly. Together
/// with the implicit `e1` centre tap of `0.5` this guarantees unity DC gain on
/// *both* polyphase branches, which is what keeps the interpolator from
/// producing a level ripple at the 2x rate.
///
/// `attenuation_db` is the design stopband attenuation; it selects the Kaiser
/// shape parameter via Kaiser's empirical formula
/// `beta = 0.1102 * (A - 8.7)` (valid for `A > 50 dB`).
pub fn design_halfband<const TAPS: usize>(attenuation_db: f64) -> [f32; TAPS] {
    let n = 2 * TAPS - 1;
    let m = (n - 1) as f64 / 2.0;
    let beta = 0.1102 * (attenuation_db - 8.7);
    let i0_beta = bessel_i0(beta);

    let mut branch = [0.0f32; TAPS];
    let mut sum = 0.0f64;
    for (i, coefficient) in branch.iter_mut().enumerate() {
        // `e0[i] = h[2i]`: only the even prototype indices land in this branch.
        let k = (2 * i) as f64;
        let offset = k - m;
        // Kaiser window evaluated at prototype index `k`.
        let ratio = (k - m) / m;
        let window = bessel_i0(beta * (1.0 - ratio * ratio).max(0.0).sqrt()) / i0_beta;
        let tap = 0.5 * sinc(0.5 * offset) * window;
        sum += tap;
        *coefficient = tap as f32;
    }

    // Exact DC normalization to 0.5 per branch.
    let scale = (0.5 / sum) as f32;
    for coefficient in branch.iter_mut() {
        *coefficient *= scale;
    }
    branch
}

/// One 2x half-band stage: interpolator and decimator sharing a coefficient
/// set but keeping independent delay lines.
///
/// `TAPS` is the length of the `e0` polyphase branch and must be a multiple of
/// 8 so the dot product vectorizes cleanly into [`f32x8`] lanes, and at most
/// `LINE` so the doubled history buffer stays contiguous.
#[repr(align(64))]
#[derive(Debug, Clone)]
pub struct HalfBandStage<const TAPS: usize> {
    /// `e0` polyphase branch, `sum == 0.5`.
    coefficients: [f32; TAPS],
    /// Interpolator history, mirrored so `[pos .. pos + TAPS]` is always a
    /// contiguous, in-order view of the last `TAPS` inputs.
    up_line: [f32; LINE * 2],
    /// Decimator history for the even sub-sequence `v[2n]`, mirrored likewise.
    down_line: [f32; LINE * 2],
    /// Decimator history for the odd sub-sequence `v[2n - 1]`, which only ever
    /// feeds the bare `0.5` centre tap.
    down_delay: [f32; LINE],
    up_pos: usize,
    down_pos: usize,
    down_delay_pos: usize,
}

impl<const TAPS: usize> Default for HalfBandStage<TAPS> {
    fn default() -> Self {
        Self {
            coefficients: [0.0; TAPS],
            up_line: [0.0; LINE * 2],
            down_line: [0.0; LINE * 2],
            down_delay: [0.0; LINE],
            up_pos: 0,
            down_pos: 0,
            down_delay_pos: 0,
        }
    }
}

impl<const TAPS: usize> HalfBandStage<TAPS> {
    /// Index *within the `e1` branch* of the prototype's centre tap.
    ///
    /// The centre sits at prototype index `M = TAPS - 1`, which is odd, so it
    /// lands in `e1` at `i` where `2i + 1 = TAPS - 1`, i.e. `TAPS / 2 - 1`.
    /// For `TAPS = 48` that is branch index 23, not 47 — the branch runs at
    /// half the prototype's rate.
    const CENTRE: usize = TAPS / 2 - 1;

    /// Designs the coefficients and clears all state.
    ///
    /// Performs the only heap-free-but-transcendental work of the filter; call
    /// it from `initialize()`, never from `process()`.
    pub fn prepare(&mut self, attenuation_db: f64) {
        debug_assert!(
            TAPS.is_multiple_of(8),
            "TAPS must be a multiple of the SIMD width"
        );
        debug_assert!(TAPS <= LINE, "TAPS must fit the mirrored delay line");
        self.coefficients = design_halfband::<TAPS>(attenuation_db);
        self.reset();
    }

    /// Clears every delay line without re-running the filter design.
    pub fn reset(&mut self) {
        self.up_line = [0.0; LINE * 2];
        self.down_line = [0.0; LINE * 2];
        self.down_delay = [0.0; LINE];
        self.up_pos = 0;
        self.down_pos = 0;
        self.down_delay_pos = 0;
    }

    /// Group delay of the underlying prototype, in samples at the stage's
    /// *upper* rate.
    pub const fn group_delay(&self) -> usize {
        TAPS - 1
    }

    /// Pushes `x` into a mirrored history buffer and returns the new write
    /// position. Writing each sample twice, `LINE` apart, means the most recent
    /// `TAPS` samples are always readable as one contiguous ascending slice.
    #[inline(always)]
    fn push(line: &mut [f32; LINE * 2], pos: usize, x: f32) -> usize {
        let next = (pos + LINE - 1) & (LINE - 1);
        // Bounds are structurally guaranteed (`next < LINE`), but `get_mut`
        // keeps the DSP path free of panicking index operations per
        // `CLAUDE.md` §1.
        if let Some(slot) = line.get_mut(next) {
            *slot = x;
        }
        if let Some(slot) = line.get_mut(next + LINE) {
            *slot = x;
        }
        next
    }

    /// SIMD dot product of the coefficient branch with `TAPS` contiguous
    /// history samples starting at `pos`.
    #[inline(always)]
    fn dot(&self, line: &[f32; LINE * 2], pos: usize) -> f32 {
        let history = match line.get(pos..pos + TAPS) {
            Some(slice) => slice,
            // Unreachable: `pos < LINE` and `TAPS <= LINE`.
            None => return 0.0,
        };

        let mut accumulator = f32x8::ZERO;
        let mut coefficient_lane = [0.0f32; 8];
        let mut history_lane = [0.0f32; 8];
        for (coefficients, samples) in self
            .coefficients
            .chunks_exact(8)
            .zip(history.chunks_exact(8))
        {
            coefficient_lane.copy_from_slice(coefficients);
            history_lane.copy_from_slice(samples);
            accumulator += f32x8::from(coefficient_lane) * f32x8::from(history_lane);
        }
        accumulator.reduce_add()
    }

    /// Interpolates one input sample into two output samples.
    ///
    /// `y[2n] = 2 * (e0 . x)` and `y[2n + 1] = 2 * e1[CENTRE] * x[n - CENTRE]`,
    /// where the factor of two restores unity gain after zero-stuffing.
    #[inline(always)]
    pub fn upsample(&mut self, x: f32) -> [f32; 2] {
        self.up_pos = Self::push(&mut self.up_line, self.up_pos, x);
        let even = 2.0 * self.dot(&self.up_line, self.up_pos);
        let odd = self
            .up_line
            .get(self.up_pos + Self::CENTRE)
            .copied()
            .unwrap_or(0.0);
        [even, odd]
    }

    /// Decimates one input pair into a single output sample.
    ///
    /// `y[n] = (e0 . v0) + 0.5 * v1[n - CENTRE]`, with `v0[n] = v[2n]` and
    /// `v1[n] = v[2n - 1]`.
    #[inline(always)]
    pub fn downsample(&mut self, x: [f32; 2]) -> f32 {
        // `x[0]` is the even phase; `x[1]` is the odd phase and belongs to the
        // branch that is a bare half-scaled delay.
        self.down_pos = Self::push(&mut self.down_line, self.down_pos, x[0]);
        let even = self.dot(&self.down_line, self.down_pos);

        // `x[1]` is `v[2n + 1]`, which is `v1[n + 1]` — one call *ahead* of the
        // `v1[n]` the sum is indexed on. Reading `CENTRE + 1` calls back
        // therefore yields the required `v1[n - CENTRE]`.
        self.down_delay_pos = (self.down_delay_pos + LINE - 1) & (LINE - 1);
        if let Some(slot) = self.down_delay.get_mut(self.down_delay_pos) {
            *slot = x[1];
        }
        let tap_index = (self.down_delay_pos + Self::CENTRE + 1) & (LINE - 1);
        let odd = self.down_delay.get(tap_index).copied().unwrap_or(0.0);

        flush(even + 0.5 * odd)
    }
}

/// Cascade of three [`HalfBandStage`]s giving the 8x rate change required by
/// specification section 2.
#[repr(align(64))]
#[derive(Debug, Clone)]
pub struct Oversampler8x {
    stage1: HalfBandStage<STAGE1_TAPS>,
    stage2: HalfBandStage<STAGE2_TAPS>,
    stage3: HalfBandStage<STAGE3_TAPS>,
    /// Scratch for the 8 oversampled samples belonging to one host sample.
    /// Pre-allocated as a fixed array so `process()` never touches the heap.
    scratch: [f32; super::OVERSAMPLING_FACTOR],
}

impl Default for Oversampler8x {
    fn default() -> Self {
        Self {
            stage1: HalfBandStage::default(),
            stage2: HalfBandStage::default(),
            stage3: HalfBandStage::default(),
            scratch: [0.0; super::OVERSAMPLING_FACTOR],
        }
    }
}

impl Oversampler8x {
    /// Designs all three stages and clears their state.
    pub fn prepare(&mut self) {
        self.stage1.prepare(STAGE1_ATTENUATION_DB);
        self.stage2.prepare(STAGE2_ATTENUATION_DB);
        self.stage3.prepare(STAGE3_ATTENUATION_DB);
        self.scratch = [0.0; super::OVERSAMPLING_FACTOR];
    }

    /// Clears all delay lines, keeping the designed coefficients.
    pub fn reset(&mut self) {
        self.stage1.reset();
        self.stage2.reset();
        self.stage3.reset();
        self.scratch = [0.0; super::OVERSAMPLING_FACTOR];
    }

    /// Round-trip latency of the up/down cascade, expressed in host samples.
    ///
    /// Stage `i` running at `2^i` times the host rate contributes `2 * M_i`
    /// samples at that rate, hence `2 * M_i / 2^i` host samples:
    ///
    /// ```text
    /// stage 1: 2 * 47 / 2 = 47
    /// stage 2: 2 * 15 / 4 =  7.5
    /// stage 3: 2 *  7 / 8 =  1.75
    /// total               = 56.25 host samples
    /// ```
    ///
    /// The value is rounded to the nearest whole sample for the host's delay
    /// compensation; the residual 0.25-sample error is far below the accuracy
    /// of any DAW's PDC and is inaudible.
    pub fn latency_samples(&self) -> u32 {
        let stage1 = 2.0 * self.stage1.group_delay() as f64 / 2.0;
        let stage2 = 2.0 * self.stage2.group_delay() as f64 / 4.0;
        let stage3 = 2.0 * self.stage3.group_delay() as f64 / 8.0;
        (stage1 + stage2 + stage3).round() as u32
    }

    /// Runs `nonlinear` at 8x the host rate for a single host sample.
    ///
    /// `nonlinear` is invoked exactly [`OVERSAMPLING_FACTOR`] times per call, in
    /// time order. It must itself be allocation-free; everything it touches
    /// lives in pre-allocated state.
    ///
    /// [`OVERSAMPLING_FACTOR`]: super::OVERSAMPLING_FACTOR
    #[inline]
    pub fn process<F>(&mut self, x: f32, mut nonlinear: F) -> f32
    where
        F: FnMut(f32) -> f32,
    {
        // Up: 1x -> 2x -> 4x -> 8x.
        let pair1 = self.stage1.upsample(x);
        let mut index = 0usize;
        for &half_rate in pair1.iter() {
            let pair2 = self.stage2.upsample(half_rate);
            for &quarter_rate in pair2.iter() {
                let pair3 = self.stage3.upsample(quarter_rate);
                for &full_rate in pair3.iter() {
                    if let Some(slot) = self.scratch.get_mut(index) {
                        *slot = nonlinear(full_rate);
                    }
                    index += 1;
                }
            }
        }

        // Down: 8x -> 4x -> 2x -> 1x, mirroring the traversal order above.
        let mut half_rate_pair = [0.0f32; 2];
        for (outer, half_rate) in half_rate_pair.iter_mut().enumerate() {
            let mut quarter_rate_pair = [0.0f32; 2];
            for (inner, quarter_rate) in quarter_rate_pair.iter_mut().enumerate() {
                let base = outer * 4 + inner * 2;
                let a = self.scratch.get(base).copied().unwrap_or(0.0);
                let b = self.scratch.get(base + 1).copied().unwrap_or(0.0);
                *quarter_rate = self.stage3.downsample([a, b]);
            }
            *half_rate = self.stage2.downsample(quarter_rate_pair);
        }
        self.stage1.downsample(half_rate_pair)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Evaluates the full half-band prototype magnitude response at a
    /// normalized frequency (cycles per sample of the upper rate) by
    /// reconstructing `h` from its `e0` branch and implicit `e1` centre tap.
    fn halfband_magnitude_db<const TAPS: usize>(branch: &[f32; TAPS], frequency: f64) -> f64 {
        let n = 2 * TAPS - 1;
        let mut real = 0.0f64;
        let mut imag = 0.0f64;
        for k in 0..n {
            let tap = if k % 2 == 0 {
                branch.get(k / 2).copied().unwrap_or(0.0) as f64
            } else if k == TAPS - 1 {
                0.5
            } else {
                0.0
            };
            let phase = -std::f64::consts::TAU * frequency * k as f64;
            real += tap * phase.cos();
            imag += tap * phase.sin();
        }
        // The prototype has unity gain at DC after the 0.5/0.5 branch split.
        20.0 * (real * real + imag * imag).sqrt().log10()
    }

    #[test]
    fn bessel_i0_matches_reference_values() {
        // Reference values from Abramowitz & Stegun table 9.8.
        assert!((bessel_i0(0.0) - 1.0).abs() < 1e-12);
        assert!((bessel_i0(1.0) - 1.266_065_877_75).abs() < 1e-9);
        assert!((bessel_i0(5.0) - 27.239_871_823_6).abs() < 1e-6);
    }

    #[test]
    fn sinc_has_unit_peak_and_integer_zeros() {
        assert!((sinc(0.0) - 1.0).abs() < 1e-12);
        for k in 1..8 {
            assert!(sinc(k as f64).abs() < 1e-12);
            assert!(sinc(-(k as f64)).abs() < 1e-12);
        }
    }

    #[test]
    fn each_branch_sums_to_exactly_half() {
        let s1 = design_halfband::<STAGE1_TAPS>(STAGE1_ATTENUATION_DB);
        let s2 = design_halfband::<STAGE2_TAPS>(STAGE2_ATTENUATION_DB);
        let s3 = design_halfband::<STAGE3_TAPS>(STAGE3_ATTENUATION_DB);
        for branch in [&s1[..], &s2[..], &s3[..]] {
            let sum: f32 = branch.iter().sum();
            assert!((sum - 0.5).abs() < 1e-6, "branch sums to {sum}");
        }
    }

    #[test]
    fn stage1_meets_its_stopband_target() {
        let branch = design_halfband::<STAGE1_TAPS>(STAGE1_ATTENUATION_DB);
        // Stopband edge 0.2841; sample the whole stopband up to Nyquist.
        let mut worst = f64::NEG_INFINITY;
        let mut f = 0.2841;
        while f <= 0.5 {
            worst = worst.max(halfband_magnitude_db(&branch, f));
            f += 0.001;
        }
        assert!(worst < -90.0, "stage 1 stopband peaked at {worst} dB");
    }

    #[test]
    fn shorter_stages_still_clear_60_db() {
        let s2 = design_halfband::<STAGE2_TAPS>(STAGE2_ATTENUATION_DB);
        let s3 = design_halfband::<STAGE3_TAPS>(STAGE3_ATTENUATION_DB);
        let mut worst2 = f64::NEG_INFINITY;
        let mut worst3 = f64::NEG_INFINITY;
        let mut f = 0.404;
        while f <= 0.5 {
            worst2 = worst2.max(halfband_magnitude_db(&s2, f));
            worst3 = worst3.max(halfband_magnitude_db(&s3, f));
            f += 0.001;
        }
        assert!(worst2 < -75.0, "stage 2 stopband peaked at {worst2} dB");
        assert!(worst3 < -65.0, "stage 3 stopband peaked at {worst3} dB");
    }

    #[test]
    fn passband_is_flat_through_20_khz() {
        let branch = design_halfband::<STAGE1_TAPS>(STAGE1_ATTENUATION_DB);
        // 20 kHz at a 48 kHz host rate is 20/96 = 0.2083 of the 2x rate.
        let mut f = 0.0;
        while f <= 0.2083 {
            let db = halfband_magnitude_db(&branch, f);
            assert!(db.abs() < 0.1, "passband ripple {db} dB at {f}");
            f += 0.002;
        }
    }

    /// Exact round-trip group delay in host samples, before the rounding that
    /// [`Oversampler8x::latency_samples`] applies for the host's benefit:
    /// `47 + 7.5 + 1.75`.
    const EXACT_LATENCY: f64 = 56.25;

    #[test]
    fn rounded_latency_matches_the_exact_group_delay() {
        let mut oversampler = Oversampler8x::default();
        oversampler.prepare();
        assert_eq!(oversampler.latency_samples(), EXACT_LATENCY.round() as u32);
    }

    #[test]
    fn transparent_round_trip_preserves_a_sine() {
        let mut oversampler = Oversampler8x::default();
        oversampler.prepare();
        let fs = 48_000.0f64;
        let f0 = 1_000.0f64;

        let mut output = Vec::with_capacity(8192);
        for n in 0..8192 {
            let x = (std::f64::consts::TAU * f0 * n as f64 / fs).sin() * 0.5;
            output.push(oversampler.process(x as f32, |s| s));
        }

        // The cascade's delay is a non-integer 56.25 samples, so the reference
        // is evaluated analytically at that fractional offset rather than by
        // indexing the input — comparing against sample 56 alone would report a
        // spurious 1.6 % error that is purely the missing quarter sample.
        let mut worst = 0.0f64;
        for n in 4_000..8_000 {
            let phase = std::f64::consts::TAU * f0 * (n as f64 - EXACT_LATENCY) / fs;
            let expected = phase.sin() * 0.5;
            let actual = output.get(n).copied().unwrap_or(0.0) as f64;
            worst = worst.max((expected - actual).abs());
        }
        assert!(worst < 1.0e-4, "round trip error {worst}");
    }

    #[test]
    fn hard_clipping_a_sine_does_not_alias() {
        // Specification section 5 / `CLAUDE.md` §5 aliasing test: drive a
        // non-linearity hard and check that no non-harmonic energy folds back.
        let fs = 48_000.0f64;
        let f0 = 4_000.0f64;
        let n = 16_384usize;

        let mut oversampler = Oversampler8x::default();
        oversampler.prepare();
        let mut samples = Vec::with_capacity(n);
        for i in 0..n {
            let x = (std::f64::consts::TAU * f0 * i as f64 / fs).sin() as f32 * 0.9;
            samples.push(oversampler.process(x, |s| s.clamp(-0.3, 0.3)));
        }

        // Goertzel probe at frequencies that are neither harmonics of 4 kHz nor
        // images of them; any energy here can only be aliasing.
        let probe = |frequency: f64| -> f64 {
            let mut real = 0.0;
            let mut imag = 0.0;
            for (i, sample) in samples.iter().enumerate().skip(n / 2) {
                let phase = std::f64::consts::TAU * frequency * i as f64 / fs;
                let hann = {
                    let t = (i - n / 2) as f64 / (n / 2) as f64;
                    0.5 - 0.5 * (std::f64::consts::TAU * t).cos()
                };
                real += *sample as f64 * hann * phase.cos();
                imag += *sample as f64 * hann * phase.sin();
            }
            let scale = 4.0 / (n / 2) as f64;
            ((real * real + imag * imag).sqrt() * scale).max(1.0e-12)
        };

        let fundamental = probe(f0);
        // 4 kHz odd harmonics land at 12/20/28/36 kHz. 28 kHz and 36 kHz would
        // alias to 20 kHz and 12 kHz without oversampling; these probes sit
        // clear of every harmonic and every image of one.
        for alias in [1_500.0, 6_500.0, 9_500.0, 14_500.0, 17_500.0] {
            let level = 20.0 * (probe(alias) / fundamental).log10();
            assert!(level < -60.0, "alias at {alias} Hz was {level} dB");
        }
    }
}
